export const COLOR_EXTENSION_MAP: { [key: string]: string } = {
  pdf: "red",
  doc: "blue",
  docx: "blue",
  xls: "green",
  xlsx: "green",
  ppt: "orange",
  pptx: "orange",
  jpg: "purple",
  jpeg: "purple",
  png: "purple",
  gif: "purple",
  svg: "purple",
  "svg+xml": "black",
  mp3: "pink",
  mp4: "pink",
  avi: "pink",
  mov: "pink",
  zip: "gray",
  rar: "gray",
  "7z": "gray",
  txt: "brown",
  other: "gray",
};
